// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8ApkE3Na0wYdwtBPAXOPSlq9fKFzsX4',
    appId: '1:38039739116:web:56b7e53da63a42c814e3c9',
    messagingSenderId: '38039739116',
    projectId: 'piiko-128cd',
    authDomain: 'piiko-128cd.firebaseapp.com',
    storageBucket: 'piiko-128cd.appspot.com',
    measurementId: 'G-SJLM57HM9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8byjBf0vjC63HbfzHs-O0rSOc4S2Pdj4',
    appId: '1:38039739116:android:586ef406d4dedaae14e3c9',
    messagingSenderId: '38039739116',
    projectId: 'piiko-128cd',
    storageBucket: 'piiko-128cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEeBDI5nPAr_hL9so8KEr1X8-pJ7gpqa8',
    appId: '1:38039739116:ios:d25e72562373472514e3c9',
    messagingSenderId: '38039739116',
    projectId: 'piiko-128cd',
    storageBucket: 'piiko-128cd.appspot.com',
    androidClientId: '38039739116-k9399csocha4gvhr7edf33lrlg70a7va.apps.googleusercontent.com',
    iosClientId: '38039739116-fjjsr18r9q2em29gd1rplaap4l04d7ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.piikoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEeBDI5nPAr_hL9so8KEr1X8-pJ7gpqa8',
    appId: '1:38039739116:ios:694d316d44c2362014e3c9',
    messagingSenderId: '38039739116',
    projectId: 'piiko-128cd',
    storageBucket: 'piiko-128cd.appspot.com',
    androidClientId: '38039739116-k9399csocha4gvhr7edf33lrlg70a7va.apps.googleusercontent.com',
    iosClientId: '38039739116-5338qsk16nejl57i65tglu2q3qk396bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.piikoApp.RunnerTests',
  );
}
